http:
  routers:
    portainer:
      rule: "Host(`pd.home.lan`)"
      service: "portainer"
      entryPoints: ["web"]
    catchall:
      rule: "HostRegexp(`{host:.+}`)"
      priority: 1
      service: "noop"
      entryPoints: ["web"]
  services:
    portainer:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:9000"
    noop:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:9999"
