name: Build VMA Image

on:
  workflow_dispatch:

jobs:
  build-vma:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build VMA
        env:
          SOURCE_DIR: ${{ github.workspace }}
          OUTPUT_DIR: ${{ github.workspace }}
        run: |
          chmod +x nixos-win/build-vma.sh
          ./nixos-win/build-vma.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nixos-vma-image
          path: "*.vma.zst"
          retention-days: 5
