name: Build VMA Image

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-vma:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build VMA
        env:
          SOURCE_DIR: ${{ github.workspace }}
          OUTPUT_DIR: ${{ github.workspace }}
        run: |
          chmod +x nixos-win/build-cloud.sh
          ./nixos-win/build-cloud.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nixos-vma-image
          path: "*.vma.zst"
          retention-days: 5

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*.vma.zst"
